name: build

on:
  workflow_dispatch:
  push:
    branches: 
    - main
    - update
  pull_request:
    branches:
    - main

jobs:
  run-tests:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      code-quality: write
      pull-requests: read

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          6.x.x
          8.x.x
          10.x.x
    - name: Run tests
      run: dotnet run -- test --parallel
      working-directory: tools/Build
    - name: Upload code coverage (artifact)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage
        path: Artifacts/coverage/**/*.cobertura.xml
        if-no-files-found: warn
    - name: Merge coverage reports
      if: always()
      run: |
        dotnet tool install -g dotnet-reportgenerator-globaltool
        reportgenerator "-reports:Artifacts/coverage/**/*.cobertura.xml" "-targetdir:Artifacts/coverage/merged" "-reporttypes:Cobertura"
    - name: Upload code coverage (GitHub)
      if: always()
      uses: actions/upload-code-coverage@v1
      with:
        file: Artifacts/coverage/merged/Cobertura.xml
        language: C#
        label: code-coverage/updatr
        fail-on-error: false
