name: post release cleanup

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["push packages"]
    types:
    - completed

jobs:
  post-release-cleanup:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.x.x
    - name: Clean up after release
      run: dotnet run -- post-release --parallel
      working-directory: tools/Build
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
