name: push packages

on:
  push:
    tags:
      - v**

jobs:
  push-packages:

    runs-on: ubuntu-latest
    environment: Push package

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x.x
    - name: Push NuGet Packages
      run: dotnet run -- push --parallel
      working-directory: tools/Build
      env:
          API_ACCESS_TOKEN: ${{ secrets.API_ACCESS_TOKEN }}
