name: create release

on:
  workflow_run:
    workflows: ["push packages"]
    types:
    - completed

jobs:
  create-release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.x.x
    - name: Create GitHub Release
      run: dotnet run -- create-release --parallel
      working-directory: tools/Build
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
