name: update packages

on: push

jobs:
  update-packages:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x.x
    - name: Update packages
      if: github.event_name == 'schedule'
      run: dotnet run -- update-packages
      working-directory: tools/Build
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Update packages and create PR
      if: github.event_name == 'push'
      run: dotnet run -- create-update-pr
      working-directory: tools/Build
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
