name: docs

on:
  workflow_dispatch:
  push:
    branches: 
    - main

jobs:
  update-docs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x.x
    - name: Update README
      run: dotnet run -- update-README --parallel
      working-directory: tools/Build
