name: Update packages

on: [ push ]

jobs:
  update-packages:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      #with:
      #  ref: main
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x.x
    - name: Update packages and create PR
      run: dotnet run -- create-update-pr
      working-directory: tools/Build
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
